### ISSUE TITLE
递交规则

### ISSUE THREAD

**Issue by Ahua9527** [Kr328/rx-block-unbrowser#3]
<prescription type="activity" package="com.netease.cloudmusic.lite" class="com.netease.cloudmusic.activity.RedirectActivity" sender="other">
    <intent-filter>
      <action name="android.intent.action.VIEW" />
      <cat name="android.intent.category.BROWSABLE" />
      <cat name="android.intent.category.DEFAULT" />
      <scheme name="http" />
      <scheme name="https" />
    </intent-filter>
  </prescription>

  
  <prescription type="activity" package="com.gzqwkj.cshu" class="com.gzqwkj.cshu.ui.activity.LauchActivity" sender="other">
    <intent-filter>
      <action name="android.intent.action.VIEW" />
      <cat name="android.intent.category.BROWSABLE" />
      <cat name="android.intent.category.DEFAULT" />
      <scheme name="http" />
      <scheme name="https" />
    </intent-filter>
  </prescription>

**Comment by Ahua9527** [comment]
<prescription type="activity" package="com.netease.cloudmusic.lite" class="com.netease.cloudmusic.activity.RedirectActivity" sender="other">
    <intent-filter>
      <action name="android.intent.action.VIEW" />
      <cat name="android.intent.category.BROWSABLE" />
      <cat name="android.intent.category.DEFAULT" />
      <scheme name="http" />
      <scheme name="https" />
    </intent-filter>
  </prescription>

  
  <prescription type="activity" package="com.gzqwkj.cshu" class="com.gzqwkj.cshu.ui.activity.LauchActivity" sender="other">
    <intent-filter>
      <action name="android.intent.action.VIEW" />
      <cat name="android.intent.category.BROWSABLE" />
      <cat name="android.intent.category.DEFAULT" />
      <scheme name="http" />
      <scheme name="https" />
    </intent-filter>
  </prescription>

**Comment by Kr328** [comment]
那么规则呢 (

**Comment by Ahua9527** [comment]
prescriptions xmlns="http://greenify.github.io/schemas/prescription/v3">
  
  <prescription type="activity" package="com.netease.cloudmusic.lite"
class="com.netease.cloudmusic.activity.RedirectActivity" sender="other">
    <intent-filter>
      <action name="android.intent.action.VIEW" />
      <cat name="android.intent.category.BROWSABLE" />
      <cat name="android.intent.category.DEFAULT" />
      <scheme name="http" />
      <scheme name="https" />
    </intent-filter>
  </prescription>

  
  <prescription type="activity" package="com.gzqwkj.cshu"
class="com.gzqwkj.cshu.ui.activity.LauchActivity" sender="other">
    <intent-filter>
      <action name="android.intent.action.VIEW" />
      <cat name="android.intent.category.BROWSABLE" />
      <cat name="android.intent.category.DEFAULT" />
      <scheme name="http" />
      <scheme name="https" />
    </intent-filter>
  </prescription>

Kr328 <notifications@github.com> 于 2019年7月6日周六 14:36写道：

**Comment by Kr328** [comment]
已添加 :)
